[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
